// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace _02.Photo.Migrations
{
    [DbContext(typeof(PhotoContext))]
    [Migration("20171025094157_AddedAlbumPictureModels")]
    partial class AddedAlbumPictureModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_01._CodeFirstStudent.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BackgroundColor");

                    b.Property<bool>("IsPublic");

                    b.Property<int>("PhotographerId");

                    b.HasKey("AlbumId");

                    b.HasIndex("PhotographerId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("_01._CodeFirstStudent.Models.Photographer", b =>
                {
                    b.Property<int>("PhotographerId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("RegisteredDate");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("PhotographerId");

                    b.ToTable("Photographers");
                });

            modelBuilder.Entity("_01._CodeFirstStudent.Models.Picture", b =>
                {
                    b.Property<int>("PictureId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Caption");

                    b.Property<string>("Path");

                    b.Property<string>("Title");

                    b.HasKey("PictureId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("_01._CodeFirstStudent.Models.PictureAlbum", b =>
                {
                    b.Property<int>("AlbumId");

                    b.Property<int>("PictureId");

                    b.HasKey("AlbumId", "PictureId");

                    b.HasIndex("PictureId");

                    b.ToTable("PictureAlbums");
                });

            modelBuilder.Entity("_01._CodeFirstStudent.Models.Album", b =>
                {
                    b.HasOne("_01._CodeFirstStudent.Models.Photographer", "Photographer")
                        .WithMany("Albums")
                        .HasForeignKey("PhotographerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("_01._CodeFirstStudent.Models.PictureAlbum", b =>
                {
                    b.HasOne("_01._CodeFirstStudent.Models.Picture", "Picture")
                        .WithMany("PictureAlbums")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("_01._CodeFirstStudent.Models.Album", "Album")
                        .WithMany("AlbumPictures")
                        .HasForeignKey("PictureId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
