ALTER TABLE Users
DROP CONSTRAINT [PK__Users__3214EC07A63EB2EE]

ALTER TABLE Users
ADD CONSTRAINT [PK__Users__3214EC07A63EB2EE] 
PRIMARY KEY (Id, Username)

ALTER TABLE Users
ADD CHECK (Password >= 5)

ALTER TABLE Users
ADD LastLoginTime datetime
DEFAULT SYSDATETIME();

ALTER TABLE Users
DROP CONSTRAINT [PK__Users__3214EC07A63EB2EE]

ALTER TABLE Users
ADD CONSTRAINT PK_Id PRIMARY KEY (Id)

ALTER TABLE Users
ADD CHECK (DATALENGTH(Username) >= 3)
 